# Generated by Django 5.2.7 on 2025-10-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('fabric', 'Fabric'), ('accessory', 'Accessory'), ('tool', 'Tool'), ('decor', 'Decor'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('donator_name', models.CharField(blank=True, max_length=100, null=True)),
                ('current_with', models.CharField(blank=True, max_length=100, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
