# Generated by Django 5.2.7 on 2025-11-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialbank', '0002_donationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('total_points', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='email',
            field=models.EmailField(default='kmitriti@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='email',
            field=models.EmailField(default='kmitriti@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
